<?php
/**
 * @file
 * Main file for badbot module.
 */

define('BADBOT_FIELD', 'badbot');
define('BADBOT_VALIDATION_FIELD', 'badbot_validate');

/*----------------------------------------------------------------------------
      CONFIG
----------------------------------------------------------------------------*/

// wishlist:
  // TODO: spam JS-detection
  // TODO: integration w/ stopforumspam.com
  // TODO: scraper honeypot
  // TODO: email honeypot
  // TODO: teergrubing ??
  // TODO: limit number of hits from same IP per time period?
  // TODO: no user agent string? block 'em

/*----------------------------------------------------------------------------
      DRUPAL HOOKS
----------------------------------------------------------------------------*/

/**
 * Implements hook_menu();
 */
function badbot_menu() {
  $items['badbot/token'] = array(
    'title' => 'Token generation',
    'page callback' => 'badbot_js_token',
    'access callback' => TRUE,
  );

  $items['admin/config/system/badbot'] = array(
    'title' => 'Badbot',
    'description' => 'Configuration page for Badbot module',
    'page callback' => 'badbot_settings',
    'access arguments' => array('administer badbot'),
  );
  
  return $items;
}

/**
 * Implements hook_permissions();
 */
function badbot_permission() {
  return array(
    'administer badbot' => array(
      'title' => t('Administer badbot'), 
      'description' => t('Administer settings for Badbot.'),
    ),
  );
}

/**
 * Implements hook_form_alter();
 */
function badbot_form_alter(&$form, &$form_state, $form_id) {
  $form_ids = &drupal_static(__FUNCTION__);

  if (!isset($form_ids)) {
    $form_ids = array();
  }

  $patterns = array(
    '^comment_node_',
    '^contact_site_form',
    '^user_register_form'
  );

  $valid = FALSE;
  foreach ($patterns as $pattern) {
    if (preg_match('`' . $pattern . '`', $form_id)) {
      $valid = TRUE;
      break;
    }
  }

  if ($valid && variable_get('badbot_forms_salt', FALSE)) {

    // include our core JS
    drupal_add_js(drupal_get_path('module', 'badbot') . '/js/badbot.js');

    $form['badbot_wrapper'] = array(
      '#type' => 'fieldset',
      '#title' => t('SpamBot Fields'),
      '#description' => t('If you see these fields, something is wrong.'),
      '#attributes' => array(
        'class' => array('element-hidden'),
      ),
    );

    // create validation field which will be populated with the token upon form submission;
    // this field is hidden from view, so normal users will never see it.
    $form['badbot_wrapper'][BADBOT_FIELD] = array(
      '#type' => 'textfield',
      '#default_value' => user_password(),
      '#title' => t('SpamBot seed'),
      '#description' => t('If you see this field, something is wrong.'),
    );
    $form['badbot_wrapper'][BADBOT_VALIDATION_FIELD] = array(
      '#type' => 'textfield',
      '#title' => t('SpamBot hash'),
      '#description' => t('If you see this field, something is wrong.'),
    );
    $form['badbot_wrapper']['last_name'] = array(
      '#type' => 'textfield',
      '#title' => t('SpamBot catch'),
      '#description' => t('If you see this field, something is wrong.'),
    );

    // track our form id & relevant fields and save to Drupal.settings for access from our
    // core JS.
    $form_ids[] = array(
      'form_id' => $form['#id'],
      'field' => BADBOT_FIELD,
      'validation_field' => BADBOT_VALIDATION_FIELD,
    );

    drupal_add_js(array(
      'badbot' => array(
        'base_path' => url('', array('absolute' => TRUE)),
        'forms' => $form_ids,
      ),
    ), 'setting');

    // validation handler to check the token.
    $form['#validate'][] = 'badbot_form_validate';
  }
}

/*----------------------------------------------------------------------------
      CALLBACKS
----------------------------------------------------------------------------*/

/**
 * Callback for /admin/config/system/badbot
 */
function badbot_settings() {
  $output = array();
  $output[] = drupal_get_form('badbot_settings_form');
  return $output;
}

/**
 * Callback for /badbot/token
 * @return [type] [description]
 */
function badbot_js_token($field_data, $return = FALSE) {
  $token = md5(variable_get('badbot_forms_salt', FALSE) . $field_data);

  if ($return) {
    return $token;  
  }
  else {
    echo $token;
    exit();   
  }
}

/*----------------------------------------------------------------------------
      FORMS
----------------------------------------------------------------------------*/

/**
 * Main module settings form.
 * @param  [type] $form       [description]
 * @param  [type] $form_state [description]
 * @return [type]             [description]
 */
function badbot_settings_form($form, &$form_state) {
  $form['badbot'] = array(
    '#type' => 'vertical_tabs',
  );

  $form['badbot']['forms'] = array(
    '#title' => t('Forms'),
    '#type' => 'fieldset',
    '#description' => t('Enable JavaScript detection on select forms.') . '<br/><br />',
  );

  $form['badbot']['forms']['badbot_forms_salt'] = array(
    '#title' => t('Salt'),
    '#type' => 'textfield',
    '#description' => t("This salt is used during the field hashing process. A salt had been genererated
                         for you when the module was installed, but you're free to change it. If you 
                         don't know the consenquences of changing this value, it's best to leave it alone.") .
                      ' <strong>' . t('Do not disclose this value to anyone. Treat it as you would a password.') . '</strong>' ,
    '#default_value' => variable_get('badbot_forms_salt'),
  );

  return system_settings_form($form);
}

/**
 * Form validation handler for JavaScript-check enabled forms.
 */
function badbot_form_validate($form, &$form_state) {
  $error = FALSE;

  // ensure the token is what we expect it to be
  if (!isset($form_state['values'][BADBOT_VALIDATION_FIELD])
    || badbot_js_token($form_state['values'][BADBOT_FIELD], TRUE) != $form_state['values'][BADBOT_VALIDATION_FIELD]) {
    $error = TRUE;
    watchdog('badbot', 'Blocked form submission. (Bad token)');
  }

  // Was it the empty field?
  if ($form_state['values']['last_name']) {
    $error = TRUE;
    watchdog('badbot', 'Blocked form submission. (Non empty field: @value)', array('@value' => $form_state['values']['last_name']));
  }

  if ($error) {
    $error_message = t('Sorry, our spam system has flagged your account. Possible reasons for this include:');

    $reasons = array();
    $reasons[] = t('You have Javascript turned off.');
    $reasons[] = t('Your email or IP address has been flagged as spam by third party services.');

    $error_message .= '<div class="badbot-block-reasons">' . theme('item_list', array('items' => $reasons)) .'</div>';
    $error_message .= t('For assistance, please contact the site administrator.');

    form_set_error('', $error_message);
    drupal_add_http_header('Status', '403 Forbidden');
  }
}

/*----------------------------------------------------------------------------
      INTERNAL
----------------------------------------------------------------------------*/